environment:
  matrix:
    - nodejs_version: "4.7"
    - nodejs_version: "5.12"
    - nodejs_version: "6.9"
    - nodejs_version: "7.5"
services:
  - mongodb
cache:
  - node_modules
install:
  - npm install
build: off
test_script:
  - npm run test
version: "{build}"